# Site settings
title: Tom Kerr
email: connect@tdkerr.ca
description: >-
  Young professional working in government QA, interested in tech policy,
  art, and travel. This is my personal space for projects and thoughts.
url: "https://tdkerr.ca" # Your site URL
domain: "tdkerr.ca" # Your domain for webmentions

  # Author info
author:
  name: "Tom Kerr"

# Social links
social:
  email: connect@tdkerr.ca
  github: TDK250  # optional
  linkedin: tdkerr  # optional

# Build settings
markdown: kramdown
highlighter: rouge

# Basic plugins that should be available
plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
